# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(891, 524)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gbCamera = QtWidgets.QGroupBox(self.centralwidget)
        self.gbCamera.setEnabled(True)
        self.gbCamera.setObjectName("gbCamera")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gbCamera)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lblCamera = QtWidgets.QLabel(self.gbCamera)
        self.lblCamera.setText("")
        self.lblCamera.setObjectName("lblCamera")
        self.gridLayout_4.addWidget(self.lblCamera, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.gbCamera, 1, 1, 1, 1)
        self.gbCameraSideView = QtWidgets.QGroupBox(self.centralwidget)
        self.gbCameraSideView.setEnabled(True)
        self.gbCameraSideView.setMaximumSize(QtCore.QSize(16777215, 250))
        self.gbCameraSideView.setObjectName("gbCameraSideView")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gbCameraSideView)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblIn = QtWidgets.QLabel(self.gbCameraSideView)
        self.lblIn.setObjectName("lblIn")
        self.gridLayout_2.addWidget(self.lblIn, 0, 2, 1, 1)
        self.pbShow = QtWidgets.QPushButton(self.gbCameraSideView)
        self.pbShow.setObjectName("pbShow")
        self.gridLayout_2.addWidget(self.pbShow, 0, 5, 1, 1)
        self.lblPosition = QtWidgets.QLabel(self.gbCameraSideView)
        self.lblPosition.setObjectName("lblPosition")
        self.gridLayout_2.addWidget(self.lblPosition, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 4, 1, 1)
        self.sbPositionValue = QtWidgets.QSpinBox(self.gbCameraSideView)
        self.sbPositionValue.setMinimum(1)
        self.sbPositionValue.setObjectName("sbPositionValue")
        self.gridLayout_2.addWidget(self.sbPositionValue, 0, 3, 1, 1)
        self.cbPosition = QtWidgets.QComboBox(self.gbCameraSideView)
        self.cbPosition.setObjectName("cbPosition")
        self.cbPosition.addItem("")
        self.cbPosition.addItem("")
        self.gridLayout_2.addWidget(self.cbPosition, 0, 1, 1, 1)
        self.lblCameraSideView = QtWidgets.QLabel(self.gbCameraSideView)
        self.lblCameraSideView.setText("")
        self.lblCameraSideView.setObjectName("lblCameraSideView")
        self.gridLayout_2.addWidget(self.lblCameraSideView, 1, 0, 1, 6)
        self.gridLayout.addWidget(self.gbCameraSideView, 2, 1, 1, 1)
        self.gbPhase = QtWidgets.QGroupBox(self.centralwidget)
        self.gbPhase.setEnabled(False)
        self.gbPhase.setObjectName("gbPhase")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gbPhase)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 5, 1, 1)
        self.sbX = QtWidgets.QSpinBox(self.gbPhase)
        self.sbX.setMaximumSize(QtCore.QSize(52, 32))
        self.sbX.setMinimum(1)
        self.sbX.setObjectName("sbX")
        self.gridLayout_3.addWidget(self.sbX, 1, 2, 1, 1)
        self.lblY = QtWidgets.QLabel(self.gbPhase)
        self.lblY.setObjectName("lblY")
        self.gridLayout_3.addWidget(self.lblY, 1, 3, 1, 1)
        self.line = QtWidgets.QFrame(self.gbPhase)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 5, 1, 1, 6)
        self.sbY = QtWidgets.QSpinBox(self.gbPhase)
        self.sbY.setMaximumSize(QtCore.QSize(52, 32))
        self.sbY.setMinimum(1)
        self.sbY.setObjectName("sbY")
        self.gridLayout_3.addWidget(self.sbY, 1, 4, 1, 1)
        self.lblConfidence = QtWidgets.QLabel(self.gbPhase)
        self.lblConfidence.setObjectName("lblConfidence")
        self.gridLayout_3.addWidget(self.lblConfidence, 6, 2, 1, 1)
        self.pbOptimize = QtWidgets.QPushButton(self.gbPhase)
        self.pbOptimize.setObjectName("pbOptimize")
        self.gridLayout_3.addWidget(self.pbOptimize, 6, 6, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 6, 5, 1, 1)
        self.lblX = QtWidgets.QLabel(self.gbPhase)
        self.lblX.setObjectName("lblX")
        self.gridLayout_3.addWidget(self.lblX, 1, 1, 1, 1)
        self.pbUpdate = QtWidgets.QPushButton(self.gbPhase)
        self.pbUpdate.setObjectName("pbUpdate")
        self.gridLayout_3.addWidget(self.pbUpdate, 1, 6, 1, 1)
        self.pbAlign = QtWidgets.QPushButton(self.gbPhase)
        self.pbAlign.setObjectName("pbAlign")
        self.gridLayout_3.addWidget(self.pbAlign, 6, 1, 1, 1)
        self.lblPhase = QtWidgets.QLabel(self.gbPhase)
        self.lblPhase.setText("")
        self.lblPhase.setObjectName("lblPhase")
        self.gridLayout_3.addWidget(self.lblPhase, 0, 1, 1, 6)
        self.gridLayout.addWidget(self.gbPhase, 1, 0, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 891, 30))
        self.menubar.setObjectName("menubar")
        self.mnFile = QtWidgets.QMenu(self.menubar)
        self.mnFile.setObjectName("mnFile")
        self.mnHelp = QtWidgets.QMenu(self.menubar)
        self.mnHelp.setObjectName("mnHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actQuit = QtWidgets.QAction(MainWindow)
        self.actQuit.setObjectName("actQuit")
        self.actLoadImage = QtWidgets.QAction(MainWindow)
        self.actLoadImage.setObjectName("actLoadImage")
        self.actAbout = QtWidgets.QAction(MainWindow)
        self.actAbout.setObjectName("actAbout")
        self.mnFile.addAction(self.actLoadImage)
        self.mnFile.addSeparator()
        self.mnFile.addAction(self.actQuit)
        self.mnHelp.addAction(self.actAbout)
        self.menubar.addAction(self.mnFile.menuAction())
        self.menubar.addAction(self.mnHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.cbPosition.setCurrentIndex(1)
        self.actQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.sbX, self.pbUpdate)
        MainWindow.setTabOrder(self.pbUpdate, self.pbOptimize)
        MainWindow.setTabOrder(self.pbOptimize, self.cbPosition)
        MainWindow.setTabOrder(self.cbPosition, self.sbPositionValue)
        MainWindow.setTabOrder(self.sbPositionValue, self.pbShow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Otimizar padrão de fase"))
        self.gbCamera.setTitle(_translate("MainWindow", "Câmera"))
        self.gbCameraSideView.setTitle(_translate("MainWindow", "Vista lateral"))
        self.lblIn.setText(_translate("MainWindow", "em"))
        self.pbShow.setText(_translate("MainWindow", "&Visualizar"))
        self.lblPosition.setText(_translate("MainWindow", "Posição"))
        self.cbPosition.setItemText(0, _translate("MainWindow", "X"))
        self.cbPosition.setItemText(1, _translate("MainWindow", "Y"))
        self.gbPhase.setTitle(_translate("MainWindow", "Padrão de fase"))
        self.sbX.setToolTip(_translate("MainWindow", "<html><head/><body><p>Indica a posição X do padrão de fase no canvas do SLM</p></body></html>"))
        self.sbX.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.lblY.setText(_translate("MainWindow", "Posição Y:"))
        self.sbY.setToolTip(_translate("MainWindow", "<html><head/><body><p>Indica a posição Y do padrão de fase no canvas do SLM</p></body></html>"))
        self.sbY.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.lblConfidence.setText(_translate("MainWindow", "Nível de confidência: "))
        self.pbOptimize.setText(_translate("MainWindow", "&Otimizar"))
        self.lblX.setText(_translate("MainWindow", "Posição X:"))
        self.pbUpdate.setText(_translate("MainWindow", "A&tualizar"))
        self.pbAlign.setText(_translate("MainWindow", "A&linhar"))
        self.mnFile.setTitle(_translate("MainWindow", "&Arquivo"))
        self.mnHelp.setTitle(_translate("MainWindow", "Ajuda"))
        self.actQuit.setText(_translate("MainWindow", "&Sair"))
        self.actLoadImage.setText(_translate("MainWindow", "&Carregar imagem"))
        self.actAbout.setText(_translate("MainWindow", "Sobre"))
