# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(891, 524)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gbCamera = QtWidgets.QGroupBox(self.centralwidget)
        self.gbCamera.setEnabled(True)
        self.gbCamera.setObjectName("gbCamera")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gbCamera)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lblCamera = QtWidgets.QLabel(self.gbCamera)
        self.lblCamera.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.lblCamera.setText("")
        self.lblCamera.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCamera.setObjectName("lblCamera")
        self.gridLayout_4.addWidget(self.lblCamera, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.gbCamera, 1, 1, 1, 1)
        self.gbCameraSideView = QtWidgets.QGroupBox(self.centralwidget)
        self.gbCameraSideView.setEnabled(True)
        self.gbCameraSideView.setMaximumSize(QtCore.QSize(16777215, 250))
        self.gbCameraSideView.setObjectName("gbCameraSideView")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gbCameraSideView)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblIn = QtWidgets.QLabel(self.gbCameraSideView)
        self.lblIn.setObjectName("lblIn")
        self.gridLayout_2.addWidget(self.lblIn, 0, 2, 1, 1)
        self.cbPosition = QtWidgets.QComboBox(self.gbCameraSideView)
        self.cbPosition.setObjectName("cbPosition")
        self.cbPosition.addItem("")
        self.cbPosition.addItem("")
        self.gridLayout_2.addWidget(self.cbPosition, 0, 1, 1, 1)
        self.lblCameraSideView = QtWidgets.QLabel(self.gbCameraSideView)
        self.lblCameraSideView.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.lblCameraSideView.setText("")
        self.lblCameraSideView.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCameraSideView.setObjectName("lblCameraSideView")
        self.gridLayout_2.addWidget(self.lblCameraSideView, 1, 0, 1, 6)
        self.lblPosition = QtWidgets.QLabel(self.gbCameraSideView)
        self.lblPosition.setObjectName("lblPosition")
        self.gridLayout_2.addWidget(self.lblPosition, 0, 0, 1, 1)
        self.sbPositionValue = QtWidgets.QSpinBox(self.gbCameraSideView)
        self.sbPositionValue.setMinimum(1)
        self.sbPositionValue.setMaximum(1280)
        self.sbPositionValue.setObjectName("sbPositionValue")
        self.gridLayout_2.addWidget(self.sbPositionValue, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 4, 1, 1)
        self.gridLayout.addWidget(self.gbCameraSideView, 2, 1, 1, 1)
        self.gbPhase = QtWidgets.QGroupBox(self.centralwidget)
        self.gbPhase.setEnabled(False)
        self.gbPhase.setObjectName("gbPhase")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gbPhase)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lblX = QtWidgets.QLabel(self.gbPhase)
        self.lblX.setObjectName("lblX")
        self.gridLayout_3.addWidget(self.lblX, 1, 1, 1, 1)
        self.lblConfidence = QtWidgets.QLabel(self.gbPhase)
        self.lblConfidence.setObjectName("lblConfidence")
        self.gridLayout_3.addWidget(self.lblConfidence, 7, 2, 1, 1)
        self.pbOptimize = QtWidgets.QPushButton(self.gbPhase)
        self.pbOptimize.setObjectName("pbOptimize")
        self.gridLayout_3.addWidget(self.pbOptimize, 7, 6, 1, 1)
        self.lblPhase = QtWidgets.QLabel(self.gbPhase)
        self.lblPhase.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.lblPhase.setText("")
        self.lblPhase.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPhase.setObjectName("lblPhase")
        self.gridLayout_3.addWidget(self.lblPhase, 0, 1, 1, 6)
        self.sbX = QtWidgets.QSpinBox(self.gbPhase)
        self.sbX.setMaximumSize(QtCore.QSize(52, 32))
        self.sbX.setMinimum(1)
        self.sbX.setMaximum(1280)
        self.sbX.setObjectName("sbX")
        self.gridLayout_3.addWidget(self.sbX, 1, 2, 1, 1)
        self.sbY = QtWidgets.QSpinBox(self.gbPhase)
        self.sbY.setMaximumSize(QtCore.QSize(52, 32))
        self.sbY.setMinimum(1)
        self.sbY.setMaximum(1024)
        self.sbY.setObjectName("sbY")
        self.gridLayout_3.addWidget(self.sbY, 1, 4, 1, 1)
        self.pbAlign = QtWidgets.QPushButton(self.gbPhase)
        self.pbAlign.setObjectName("pbAlign")
        self.gridLayout_3.addWidget(self.pbAlign, 7, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.gbPhase)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 6, 1, 1, 6)
        self.lblY = QtWidgets.QLabel(self.gbPhase)
        self.lblY.setObjectName("lblY")
        self.gridLayout_3.addWidget(self.lblY, 1, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 7, 5, 1, 1)
        self.sbDistanceGrating = QtWidgets.QSpinBox(self.gbPhase)
        self.sbDistanceGrating.setMaximumSize(QtCore.QSize(52, 32))
        self.sbDistanceGrating.setMinimum(1)
        self.sbDistanceGrating.setMaximum(1024)
        self.sbDistanceGrating.setObjectName("sbDistanceGrating")
        self.gridLayout_3.addWidget(self.sbDistanceGrating, 3, 2, 1, 1)
        self.sbLengthGrating = QtWidgets.QSpinBox(self.gbPhase)
        self.sbLengthGrating.setMaximumSize(QtCore.QSize(52, 32))
        self.sbLengthGrating.setMinimum(1)
        self.sbLengthGrating.setMaximum(1024)
        self.sbLengthGrating.setObjectName("sbLengthGrating")
        self.gridLayout_3.addWidget(self.sbLengthGrating, 3, 4, 1, 1)
        self.lblDistanceGrating = QtWidgets.QLabel(self.gbPhase)
        self.lblDistanceGrating.setObjectName("lblDistanceGrating")
        self.gridLayout_3.addWidget(self.lblDistanceGrating, 3, 1, 1, 1)
        self.lblLengthGrating = QtWidgets.QLabel(self.gbPhase)
        self.lblLengthGrating.setObjectName("lblLengthGrating")
        self.gridLayout_3.addWidget(self.lblLengthGrating, 3, 3, 1, 1)
        self.cbBinary = QtWidgets.QCheckBox(self.gbPhase)
        self.cbBinary.setChecked(True)
        self.cbBinary.setObjectName("cbBinary")
        self.gridLayout_3.addWidget(self.cbBinary, 3, 6, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 5, 1, 2)
        self.gridLayout.addWidget(self.gbPhase, 1, 0, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 891, 30))
        self.menubar.setObjectName("menubar")
        self.mnFile = QtWidgets.QMenu(self.menubar)
        self.mnFile.setObjectName("mnFile")
        self.mnHelp = QtWidgets.QMenu(self.menubar)
        self.mnHelp.setObjectName("mnHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actQuit = QtWidgets.QAction(MainWindow)
        self.actQuit.setObjectName("actQuit")
        self.actLoadImage = QtWidgets.QAction(MainWindow)
        self.actLoadImage.setObjectName("actLoadImage")
        self.actAbout = QtWidgets.QAction(MainWindow)
        self.actAbout.setObjectName("actAbout")
        self.actSaveImage = QtWidgets.QAction(MainWindow)
        self.actSaveImage.setObjectName("actSaveImage")
        self.actSavePhase = QtWidgets.QAction(MainWindow)
        self.actSavePhase.setObjectName("actSavePhase")
        self.actSaveGraphic = QtWidgets.QAction(MainWindow)
        self.actSaveGraphic.setObjectName("actSaveGraphic")
        self.actUpdatePhase = QtWidgets.QAction(MainWindow)
        self.actUpdatePhase.setObjectName("actUpdatePhase")
        self.mnFile.addAction(self.actLoadImage)
        self.mnFile.addSeparator()
        self.mnFile.addAction(self.actQuit)
        self.mnHelp.addAction(self.actAbout)
        self.menubar.addAction(self.mnFile.menuAction())
        self.menubar.addAction(self.mnHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.cbPosition.setCurrentIndex(1)
        self.actQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.sbX, self.sbY)
        MainWindow.setTabOrder(self.sbY, self.sbDistanceGrating)
        MainWindow.setTabOrder(self.sbDistanceGrating, self.sbLengthGrating)
        MainWindow.setTabOrder(self.sbLengthGrating, self.cbBinary)
        MainWindow.setTabOrder(self.cbBinary, self.pbAlign)
        MainWindow.setTabOrder(self.pbAlign, self.pbOptimize)
        MainWindow.setTabOrder(self.pbOptimize, self.cbPosition)
        MainWindow.setTabOrder(self.cbPosition, self.sbPositionValue)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Otimizar padrão de fase"))
        self.gbCamera.setTitle(_translate("MainWindow", "Câmera"))
        self.gbCameraSideView.setTitle(_translate("MainWindow", "Vista lateral"))
        self.lblIn.setText(_translate("MainWindow", "em"))
        self.cbPosition.setItemText(0, _translate("MainWindow", "X"))
        self.cbPosition.setItemText(1, _translate("MainWindow", "Y"))
        self.lblPosition.setText(_translate("MainWindow", "Posição"))
        self.gbPhase.setTitle(_translate("MainWindow", "Padrão de fase"))
        self.lblX.setText(_translate("MainWindow", "Posição X:"))
        self.lblConfidence.setText(_translate("MainWindow", "Nível de confidência: "))
        self.pbOptimize.setText(_translate("MainWindow", "&Otimizar"))
        self.sbX.setToolTip(_translate("MainWindow", "<html><head/><body><p>Indica a posição X do padrão de fase no canvas do SLM</p></body></html>"))
        self.sbX.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.sbY.setToolTip(_translate("MainWindow", "<html><head/><body><p>Indica a posição Y do padrão de fase no canvas do SLM</p></body></html>"))
        self.sbY.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.pbAlign.setText(_translate("MainWindow", "A&linhar"))
        self.lblY.setText(_translate("MainWindow", "Posição Y:"))
        self.lblDistanceGrating.setText(_translate("MainWindow", "Distância:"))
        self.lblLengthGrating.setText(_translate("MainWindow", "Comprimento:"))
        self.cbBinary.setText(_translate("MainWindow", "Imagem binária"))
        self.mnFile.setTitle(_translate("MainWindow", "&Arquivo"))
        self.mnHelp.setTitle(_translate("MainWindow", "A&juda"))
        self.actQuit.setText(_translate("MainWindow", "&Sair"))
        self.actLoadImage.setText(_translate("MainWindow", "&Carregar imagem"))
        self.actAbout.setText(_translate("MainWindow", "Sobre"))
        self.actSaveImage.setText(_translate("MainWindow", "Salvar imagem"))
        self.actSaveImage.setToolTip(_translate("MainWindow", "Salvar imagem"))
        self.actSavePhase.setText(_translate("MainWindow", "Salvar fase"))
        self.actSaveGraphic.setText(_translate("MainWindow", "Salvar gráfico"))
        self.actUpdatePhase.setText(_translate("MainWindow", "Atualizar"))
